minor: remove extra / in hugo_install_path

diff --git a/bin/installHugo b/bin/installHugo
--- a/bin/installHugo
+++ b/bin/installHugo
@@ -1,28 +1,53 @@
-#!/bin/bash
-set -euo pipefail
+#!/usr/bin/env sh
 
-export HUGO_VERSION="0.88.1"
+tmp=
+trap 'rm -fr -- "${tmp}"' EXIT INT
+tmp="$(mktemp)"
 
-if [ `uname` = "Linux" ]; then
-    export HUGO_OS="Linux-64bit"
-elif [ `uname` = "Darwin" ]; then
-    export HUGO_OS="macOS-64bit"
+hugo_version="0.88.1"
+
+case "$(uname)" in
+Linux) hugo_os='Linux-64bit' ;;
+Darwin) hugo_os='macOS-64bit' ;;
+*)
+  printf 'This script only works on Linux and Mac os\n' >&2
+  exit 1
+  ;;
+esac
+
+hugo_install_path="$(cd "${0%/*}" && pwd)"
+
+hugo_archive="hugo_extended_${hugo_version}_${hugo_os}.tar.gz"
+hugo_url="https://github.com/gohugoio/hugo/releases/download/v${hugo_version}/${hugo_archive}"
+
+if ! command -v hugo >/dev/null 2>&1; then
+  # If hugo is not executable or not a file it must be downloaded and installed
+  if ! { [ -x "${hugo_install_path}/hugo" ] && [ -f "${hugo_install_path}/hugo" ]; }; then
+    if ! {
+      wget "${hugo_url}" -O "${tmp}" &&
+        cd "${hugo_install_path}" &&
+        tar -xzf "${tmp}" hugo
+    }; then
+      printf 'Failed to download hugo\n' >&2
+      exit 1
+    fi
+  fi
+
+  local_bin="${HOME}/.local/bin"
+  # Hugo needs be made available in local bin path
+  mkdir -p -- "${local_bin}" &&
+  ln -sf -- "${hugo_install_path}/hugo" "${local_bin}/" &&
+  case ":$PATH:" in
+    *:${local_bin}:*) ;;
+    *)
+      export PATH="${local_bin}:${PATH#:}"
+      cat  >> "$HOME/.profile" <<EOF
+[ -d "\${HOME}/.local/bin" ] && export PATH="\${HOME}/.local/bin:\${PATH#:}"
+EOF
+      ;;
+  esac
 else
-    echo 'This script only works on Linux and Mac os'
-    exit 1
-fi
-
-cd "$( dirname "$0" )/../" && pwd
-
-if ! command -v COMMAND &> /dev/null
-then
-  wget https://github.com/gohugoio/hugo/releases/download/v${HUGO_VERSION}/hugo_extended_${HUGO_VERSION}_${HUGO_OS}.tar.gz
-
-  rm -rf hugo
-  tar -xzf hugo_extended_${HUGO_VERSION}_${HUGO_OS}.tar.gz hugo
-  rm hugo_extended_${HUGO_VERSION}_${HUGO_OS}.tar.gz
-else
-  echo 'Hugo is already installed in this environment'
+  printf 'Hugo is already installed in this environment\n'
 fi
 
 hugo version
